name: PR Workflow

on:
  pull_request:
    branches:
      - main  # Cambia 'master' por el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install  

      - name: Run lint and unit tests
        run: |
          npm run lint  # Ejecutar el comando 'lint'
          npm run test:unit  # Ejecutar el comando 'test:unit'